version: '3.4'
services:
  php:
    build:
      context: ./api
      target: php
    env_file:
      - ./api/.env
    volumes:
      - ./api:/srv/api:rw,cached

  nginx-api:
    build:
      context: ./api
      target: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro

  h2-proxy:
    # Don't use this proxy in prod
    build:
      context: ./h2-proxy
    depends_on:
      - nginx-api
    ports:
      - "443:443"