users.get:
    path: "/api/users"
    methods: GET
    controller: App\TestTaker\Http\Controller\UserController:index

users.get.by.id:
    path: "/api/user/{id}"
    methods: GET
    controller: App\TestTaker\Http\Controller\UserController:user