NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
  prefix:   /

aurora:
  # loads routes from the YAML or XML files found in some bundle directory
  resource: '../src/TestTaker/Resources/routing/'
  type:     directory